version: '3'
services:
  etcd:
    image: bitnami/etcd
    ports:
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - apisix-network

  apisix:
    image: apache/apisix
    ports:
      - 9080:9080
    volumes:
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    networks:
      - apisix-network

networks:
  apisix-network:
