version: '3'
services:
   apisix:
    image: apache/apisix
    ports:
      - 9080:9080
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - APISIX_STAND_ALONE=true
    volumes:
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml
