version: '3'
services:
  apisix:
    image: apache/apisix
    ports:
      - 9080:9080
    entrypoint: ["sh","-c"]
    command: ["/usr/bin/apisix init && exec /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"]
    volumes:
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8080:80


