
deployment:
  role: traditional
  role_traditional:
      config_provider: etcd
  apisix:
    node_listen:
      - 0.0.0.0:9080
  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30 
